/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:27019828-3890-4e37-80b4-1b84e92a39b5",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "aa5337540f994a5b903621a633e065ef",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
