/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8e0b9cec-b752-4c2a-9af0-d5b0062549da",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "eee36106e16046c8b887aa0daff76bc3",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
